#!/bin/sh

# ffmpeg is exist or not
if test ! -d  `pwd`/ffmpeg; then
    git submodule init;
    git submodule update;
    patch -p1 < `pwd`/contrib/ffmpeg-unicode.patch
fi

# exec autoreconf
autoreconf -vi -I `pwd`/m4